### ISSUE TITLE
OffCanvas

### ISSUE THREAD

**Issue by metadan** [juliancwirko/meteor-npm-foundation-test#4]
Can you add a demonstration of how to use offcanvas with this?

**Comment by juliancwirko** [comment]
Hi, unfortunatelly I don't plan to do this here, but you could take a look at the demo repo of Foundation 5 package for meteor. There is offcanvas implementation and many other demo F5 plugins. Main concept should be the same. 

Here is the repo: [https://github.com/juliancwirko/meteor-zf5-demo](https://github.com/juliancwirko/meteor-zf5-demo)
And demo website: [zf5.meteorapp.com](zf5.meteorapp.com)
